### ISSUE TITLE
ClassCastExceptions after unexpected exceptions in listeners or during unpacking

### ISSUE THREAD

**Issue by rkrell** [izpack/izpack#363]
There is a regression in 5.0 RC5 in exception handling:

If there are problems in the user part of the installer, like
```
Jun 9, 2015 6:13:22 PM SEVERE: Failed to unpack pack: Application
com.izforge.izpack.api.exception.InstallerException: Failed to unpack pack: Application
	at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:496)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:425)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:253)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.run(UnpackerBase.java:235)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /home/rkrell/superapp/bin/wrapper-linux-x86-64/wrapper (Text file busy)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.izforge.izpack.installer.unpacker.FileUnpacker.getTarget(FileUnpacker.java:230)
	at com.izforge.izpack.installer.unpacker.FileUnpacker.copy(FileUnpacker.java:129)
	at com.izforge.izpack.installer.unpacker.DefaultFileUnpacker.unpack(DefaultFileUnpacker.java:65)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.extract(UnpackerBase.java:622)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:586)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:478)
	... 4 more
```
or NullPointerErrors this results in running into an unexpected ClassCastException:
```
Exception in thread "IzPack - Unpacker thread" java.lang.ClassCastException: java.io.FileNotFoundException cannot be cast to com.izforge.izpack.api.exception.IzPackException
	at com.izforge.izpack.installer.unpacker.UnpackerBase.unpack(UnpackerBase.java:273)
	at com.izforge.izpack.installer.unpacker.UnpackerBase.run(UnpackerBase.java:235)
	at java.lang.Thread.run(Thread.java:745)
```

The exception cause should be caught in a more robust manner, to avoid the latter ClassCastException.

**Comment by rkrell** [comment]
Already fixed.
